spring:
  application:
    name: car-system-management
  datasource:
    url: jdbc:postgresql://localhost:6000/car_system_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080


openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0



# Logging
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: INFO
    org.example: DEBUG